package dialect

import org.seasar.doma.jdbc.dialect.*

object Oracle12Dialect : OracleDialect() {

    override fun supportsIdentity() = true

    override fun supportsAutoGeneratedKeys() = true
    
}