package config

import org.seasar.doma.jdbc.*
import org.seasar.doma.jdbc.command.*
import org.seasar.doma.jdbc.query.*
import java.lang.reflect.*
import java.sql.*

object Oracle12CommandImplementors : CommandImplementors {
    override fun createInsertCommand(method: Method, query: InsertQuery): InsertCommand {
        return object : InsertCommand(query) {
            override fun prepareStatement(connection: Connection): PreparedStatement {
                return if (query.isAutoGeneratedKeysSupported) {
                    return connection.prepareStatement(sql.rawSql, intArrayOf(1))
                } else {
                    super.prepareStatement(connection)
                }
            }
        }
    }

    override fun createBatchInsertCommand(method: Method, query: BatchInsertQuery): BatchInsertCommand {
        return object: BatchInsertCommand(query) {
            override fun prepareStatement(connection: Connection, sql: PreparedSql): PreparedStatement {
                return if (query.isAutoGeneratedKeysSupported) {
                    return connection.prepareStatement(sql.rawSql, intArrayOf(1))
                } else {
                    super.prepareStatement(connection, sql)
                }
            }
        }
    }
}

